spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_services_spring
    username: postgres
    password: 99497
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: false
  main:
    allow-circular-references: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: hasan.rahimi@gmail.com
    password: rwmunnrcndyhjjvy
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transfer:
          protocol: smtp
    test-connection: false